version: '3'
services:
  app:
    build:
      context: ./app
    image: cyberjoda/my-app:latest
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
    image: cyberjoda/my-nginx:latest
    ports:
      - "80:80"