version: '3'

services:
  app:
    image: my-dockerhub-username/my-microservice:latest
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf