name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover -s tests
    - name: Build and push Docker image
      run: |
        docker build -t my-microservice:latest .
        docker tag my-microservice:latest my-dockerhub-username/my-microservice:latest
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push my-dockerhub-username/my-microservice:latest
    - name: Deploy to production
      if: github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to production"